# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AhadAlbaqami_Assessment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya', '~> 15.0'

  # Pods for AhadAlbaqami_Assessment

  target 'AhadAlbaqami_AssessmentTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
